Dev mm identity
MlabCommunity/identity pull request #1
Opened 2022-07-18 13:30 UTC by Madzionator

2022-07-21 07:23 UTC, adambednarz requested changes
Ogólnie spoko, bardzo fajnie że użyłeś CQRSa
ale kilka głównych uwag

1. Czasami mylisz query z command np przy logowaniu
2. Zastanów się czy IAppUserRepository powinno być w warstwie aplikacji  i czy  nie powinno mieć może wszystkich metod CRUD?
3. Wspominałem że QueryHandlery dobrze mieć w warstwie Infrastruktury i podczas zapytań bazować na dbContext zastanów się czy u siebie też możesz to zaimplementować
4. Zdaje się że brakuje inicjalizacji usera
5. Rozważ dodanie Base controllera i wyciąganie w nim UserId za pomocą Twojego providera 
6. Modele Requestów trzymamy w API

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Commands/Handlers/UpdateUserEmailCommandHandler.cs
> +        var user = await _userInfoProvider.GetCurrentUser();
To co wyżej

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Commands/Handlers/UpdateUserDataCommandHandler.cs
> +        var user = await _userInfoProvider.GetCurrentUser();
UserInfoProvider zrobił się tworem który przecina wszystkie warstwy i częśc ciągnie z httpContext a część z dbContext oj to słaby pomysł.
Zastanów się czy nie ma tu gdzieś miejsca na repozytorium ;)

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Commands/Handlers/UpdateUserPasswordCommandHandler.cs
> +        var user = await _userInfoProvider.GetCurrentUser();
To co wyżej

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Interfaces/IAppTokenRepository.cs
> +namespace Lapka.Identity.Application.Interfaces;
Czemu ten interfejs znalazł się w warstwie Aplikacji?? Nie za wysoko ?

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Interfaces/IAppUserRepository.cs
> +namespace Lapka.Identity.Application.Interfaces;
To co wyżej

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Interfaces/IAppUserRepository.cs
> +public interface IAppUserRepository
Repozytorium implementować powinno co najmniej CRUDa to może coś by tu dorzucić i zastanowić się jak połączyć userMenagera z Repozytorium?

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Queries/Handlers/GetUserDataByIdQueryHandler.cs
> +        var user = await _appUserRepository.GetFullUserById(query.Id);
Nie jest to źle ale ostatnio przed wyjściem wspominałem Wam, że warto query handlery mieć w infrastrukturze i wykorzystywać w nich bezpośrednio dbContext mamy wtedy dużo większą elastyczność w budowie query

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Queries/Handlers/GetUserDataQueryHandler.cs
> +        var user = await _userInfoProvider.GetCurrentUser();
To co wcześniej w komendach

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Queries/Handlers/UseRefreshTokenQueryHandler.cs
> +        if (appToken.CreatedAt.AddMonths(_jwtSettings.RefreshExpiryMonths) < DateTime.UtcNow)
Aż miesiąc? :D

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/Queries/Handlers/UseRefreshTokenQueryHandler.cs
> +            await _appTokenRepository.RemoveRefreshToken(appToken);
wykonujesz pewną operację na bazie czy zatem to ma być query???

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/RequestWithValidation/SetNewPasswordRequest.cs
> +namespace Lapka.Identity.Application.Validation.RequestWithValidation;
namespace

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/RequestWithValidation/UserEmailRequest.cs
> +namespace Lapka.Identity.Application.Validation.RequestWithValidation;
namespace

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/RequestWithValidation/UserPasswordRequest.cs
> +namespace Lapka.Identity.Application.Validation.RequestWithValidation;
namespace

2022-07-21 07:23 UTC, adambednarz commented on Lapka.Identity.Application/LoginProvider.cs
> +    ResetPassword,
ResetPassword to login provider?

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Application/CommandHandlers/UpdateUserEmailCommandHandler.cs
> +
generowanie tokenów zmiany hasła, zmiany i potwierdzenia maila dostarcza nam Identity więc chyba bezpieczniej jest użyć ich funkcji które zwracają hash niż pchać w claimsy Id i Email. Np: ktoś wejdzie w postmana i wklei sobie Id i email użytkownika który jest widoczny

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Application/CommandHandlers/UpdateUserEmailCommandHandler.cs
> +        }
Wydaje mi się że każdy serwis powinien mieć osobne wyjątki czyli np jeżeli po użyciu metody coś się nie powiedzie po stronie innego serwisu to serwis w którym coś nie zadziałało powinien wyrzucić wyjątek np z internalem

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Application/CommandHandlers/UpdateUserPasswordCommandHandler.cs
> +        }
Imo ta pierwsza walidacja Guid.Empty troszkę nie ma sensu bo jeżeli będzie pusty to nie znajdzie usera

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Application/DTO/ConfirmEmailAddressDTO.cs
> +public record ConfirmEmailAddressDTO(string Email, string Token, string Username, string FirstName, string LastName, Guid UserId);
Dto jako rekord?

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Application/Queries/GetUserDataByIdQuery.cs
> +public record GetUserDataByIdQuery(Guid Id) : IQuery<GetUserDataQueryResult>;
Query chyba nie powinno być rekordem. Tak samo w wielu miejscach

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Application/Queries/GetUserDataQuery.cs
> +public record GetUserDataQueryResult(Guid Id, string Username, string FirstName, string LastName, string Email, DateTime CreatedAt);
single responsibility

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Core/Domain/Entities/UserExtended.cs
> +        }
anemiczna encja

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Core/Domain/TimeInterfaces.cs
> +}
Imo single responsibility

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Core/Lapka.Identity.Core.csproj
> +</Project>
EF w core

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Infrastructure/DataBase/DataContext.cs
> +    }
Trzeba Adama dopytać bo wszystkich userów tworzymy przez managera a tutaj user jest na sztywno wklepywany

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Infrastructure/Exceptions/ExceptionMiddleware.cs
> +    }
Imo warto dodać  RpcException z internalem

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Infrastructure/Repository/AppTokenRepository.cs
> +        };
Imo takie rzeczy powinny być w handlerze i przekazywane do repo

2022-08-07 21:45 UTC, anieckarz-src commented on Lapka.Identity.Infrastructure/gRPC/NotificationGrpcClient.cs
> +}
Imo to powinno być w notyfikacji wyrzucane

2022-08-07 21:45 UTC, anieckarz-src commented on docker-compose.yml
> +    volumes:
Imo porty powinny zostać domyślne i wszystkie serwisy używać jednego kontenera z bazą danych

2022-08-08 08:02 UTC, Madzionator commented on Lapka.Identity.Api/Controllers/AuthController.cs
> +    [HttpPost("setNewPassword/{token}")]
zgadzam się ale jednocześnie musi być jasne o co chodzi, password to nie wiadomo czy wysyłasz prośbę o zmianę, czy edytujesz jako zalogowany użytkownik bez potwierdzenia, czy jako niezalogowany na podstawie linku. możliwe że da się skrócić ale długie nie jest myślę 😅

2022-08-08 08:06 UTC, Madzionator commented on Lapka.Identity.Api/Helpers/UserInfoProvider.cs
> +}
tak na razie tak jest, ale z założenia kiedyś mogłyby dojść inne podstawowe rzeczy potrzebne więc już zostawiłam tak by łatwiej rozszerzać kiedyś.

2022-08-08 08:08 UTC, Madzionator commented on Lapka.Identity.Application/CommandHandlers/UpdateUserEmailCommandHandler.cs
> +
to co piszesz to ew kwestia bezpieczeństwa więc sama nie wiem jak lepiej, mam nadzieję że Adam się wypowie 😁. Na pewno to rozwiązanie którego użyłam jest pomocne i łatwe w użyciu.

2022-08-08 08:20 UTC, Madzionator commented on Lapka.Identity.Application/CommandHandlers/UpdateUserEmailCommandHandler.cs
> +        }
ogólnie użycie tutaj try catch to moje przeoczenie bo przeniosłam w inne miejsce i zapomniałam tu usunąć, ale co do samego błędu to dla użytkownika (frontu) liczy się tylko to że z jakiegoś powodu nie udało się wysłać maila i ma błąd 500, pod spodem jest sklejana wiadomość że finalnie dostaje "Nie udało sie wysłać wiadomości. {powód}. Obsługa tych błędów przechwytywana jest w NotificationGrpcClient

2022-08-08 08:21 UTC, Madzionator commented on Lapka.Identity.Application/DTO/ConfirmEmailAddressDTO.cs
> +public record ConfirmEmailAddressDTO(string Email, string Token, string Username, string FirstName, string LastName, Guid UserId);
jak najbardziej, to aż się prosi 😀

2022-08-08 08:22 UTC, Madzionator commented on Lapka.Identity.Application/Queries/GetUserDataByIdQuery.cs
> +public record GetUserDataByIdQuery(Guid Id) : IQuery<GetUserDataQueryResult>;
Dobrze że jest bo dzięki temu na pewno po drodze nie zmieni się ani zapytanie ani odpowiedź.

2022-08-08 08:25 UTC, Madzionator commented on Lapka.Identity.Application/Queries/GetUserDataQuery.cs
> +public record GetUserDataQueryResult(Guid Id, string Username, string FirstName, string LastName, string Email, DateTime CreatedAt);
to już wyjaśniałam w PR od notification, termin ten odnosi się do jednego powodu istnienia klasy itd, a nie do tego że w jednym pliku może być tylko jedna rzecz. Jako że są to małe recordy, mocno ze sobą powiązane to czytelniej mi jest w przypadku query dawać strukture zapytania i odpowiedzi w jednym miejscu :)

2022-08-08 08:26 UTC, Madzionator commented on Lapka.Identity.Core/Domain/TimeInterfaces.cs
> +}
to też wyjaśniałam w PR od notyfikacji

2022-08-08 08:26 UTC, Madzionator commented on Lapka.Identity.Core/Lapka.Identity.Core.csproj
> +</Project>
nie rozumiem?

2022-08-08 08:31 UTC, Madzionator commented on Lapka.Identity.Infrastructure/DataBase/DataContext.cs
> +    }
Tu jest tworzenie migracji, dosyć nisko się dzieją operację i jeszcze nie mają dostępu do managera / nie byłoby to czyste, a admin to i tak user taki jedyny w swoim rodzaju, tworzony tylko raz a i tak osoba używająca tego pierwsze co zrobi to zmieni swoje dane bo są widoczne w migracji.

2022-08-08 08:32 UTC, Madzionator commented on Lapka.Identity.Infrastructure/Exceptions/ExceptionMiddleware.cs
> +    }
To jest zrobione w innym miejscu

2022-08-08 08:34 UTC, Madzionator commented on Lapka.Identity.Infrastructure/Repository/AppTokenRepository.cs
> +        };
tak mogłyby, ale myślę że tak też jest ok

2022-08-08 08:40 UTC, Madzionator commented on Lapka.Identity.Infrastructure/gRPC/NotificationGrpcClient.cs
> +}
a mi własnie podoba się użycie tego tu, bo w tym serwisie 3 metody w przypadku błędu prowadzą do tego samego -> nie udało się wysłać maila i to fajnie zachowuje zasadę DRY, jednocześnie sprawiając że gdy dojdzie kolejny serwis grps np stworzenie schroniska to już tam błąd będzie całkiem inny, a gdybyśmy łapali to dopiero w middleware to ciężko by było to rozdzielać na jednoznaczne wiadomości dla clienta.

2022-08-08 08:41 UTC, Madzionator commented on docker-compose.yml
> +    volumes:
to też wyjaśniałam w PR od notyfikacji

2022-08-09 22:08 UTC, adambednarz approved these changes
Jest klika bardzo drobnych uwag ale ogólnie mega spoko, bardzo przejrzyście i czytelnie i prawie wszystko idealnie na swoim miejscu

2022-08-09 22:08 UTC, adambednarz commented on Lapka.Identity.Application/RabbitEvents/UserDeletedEvent.cs
> +namespace Lapka.Identity.Application.RabbitEvents;
Nazwa katalogu znajdującego się w warstwie aplikacji nie powinna mieć w nazwie elementów infrastruktury, Tu możesz zastosować nazwę InternalAsExternalEvents albo OutgoingEvents

2022-08-09 22:08 UTC, adambednarz commented on Lapka.Identity.Infrastructure/JWT/JwtGenerator.cs
> +                {"email", email}
Jak wyżej wyciągnąć to jako const  klasy statycznej

2022-08-09 22:08 UTC, adambednarz commented on Lapka.Identity.Infrastructure/QueryHandlers/GetCurrentUserDataQueryHandler.cs
> +        var user = await _appUserRepository.GetUserWithExtendedById(query.Id);
To jest poprawnie ale pamiętaj, że możesz tu też korzystać bezpośrednio z kontekstu db

2022-08-10 07:13 UTC, Madzionator commented on Lapka.Identity.Api/Program.cs
> +builder.Services.AddSwaggerA();
tu chodziło o to że swagger wraz z autentykacją, ale faktycznie nieintuicyjne to jest

2022-08-11 07:18 UTC, merged