Dev an identity
MlabCommunity/identity pull request #2
Opened 2022-07-20 07:15 UTC by anieckarz-src

2022-07-21 06:43 UTC, adambednarz requested changes
Standardowo
Ogólnie spoko, bardzo fajnie że użyłeś CQRSa
ale kilka głównych uwag
1. Jako identyfikatora używamy Guid a nie string
2. Czasami mylisz query z command np przy logowaniu
3. Zastanów się czy nie powinno istnieć coś takiego jak IUserRepository? i jeżeli tak to jak mogłaby wyglądać implementacja.
4, Wspominałem że QueryHandlery dobrze mieć w warstwie Infrastruktury i podczas zapytań bazować na dbContext zastanów się czy u siebie też możesz to zaimplementować

2022-07-21 06:43 UTC, adambednarz commented on Lappka.Identity.Application/Lappka.Identity.Application.csproj
> +      <Folder Include="ExceptionsLogic" />
Niepotrzebne rzeczy też czyścimy, tutaj prawdopodobnie ide się zbugowało i Ci nie usunęło tego katalogu

2022-07-21 06:43 UTC, adambednarz commented on Lappka.Identity.Application/Auth/Queries/Handlers/LoginQueryHandler.cs
> +    public LoginQueryHandler(AppSignInManager appSignInManager,UserManager<AppUser> appUserManager, ITokenRepository tokenRepository,
Zastanów się czy aby na pewno to powinno nazywać się query czy przypadkiem nie wykonujesz jakiejś operacji na bazie?

2022-07-21 06:43 UTC, adambednarz commented on Lappka.Identity.Application/Services/AppUserManager.cs
> +
formatowanie

2022-08-07 19:53 UTC, Madzionator requested changes

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Api/Controllers/UserController.cs
> +    [HttpPatch("email/confirm")]
tutaj rozważ dodanie AllowAnonymous gdyby np ktoś potwierdzał adres z innego urządzenia niż wysłał żądanie.

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Api/Controllers/UserController.cs
> +    [HttpPatch("email/confirm")]
i btw POST lepiej pasuje do tej metody, skoro to jest potwierdzenie a nie konkretna zmiana?

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Api/appsettings.Development.json
> +      "template": "message_context"
rozważ jako template 
https://github.com/MlabCommunity/identity/blob/dev-MM-identity/Lapka.Identity.Api/appsettings.Development.json#L57
ponieważ dzięki temu nazwy kolejek tworzą się jednoznacznie i robiłam to z Adamem i tak mi zasugerował.

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Application/User/Commands/Handlers/ConfirmChangeEmailCommandHandler.cs
> +        var isCorrect = await _userRepository.CheckPasswordAsync(user, command.Password);
Osobiście nie rozumiem po co w tej komendzie hasło, szczególnie że to już potwierdzenie z linka wysłanego w mailu.

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Core/Consts/Role.cs
> +    USER=1,ORGANIZATION=2,ADMIN=3
Niepoprawne jest to formatowanie. Standard jest opisany tu: [C# Coding conventions](https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md#17-do-use-singular-names-for-enums-exception-bit-field-enums)

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Core/Entities/UserExtended.cs
> +
👀 ał, te entery

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Core/Repositories/IUserRepository.cs
> +
trochę tu tego, to nadal repozytorium czy już serwis?

Na pewno do repozytorium nie pasuje funkcja generująca token zmiany hasła czy emailu. Jak już masz w argumencie AppUser czyli pobranego usera to może przekazać go do jakiegoś serwisu.

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Infrastructure/Database/Postgres/Repositories/PostgresUserRepository.cs
> +    public async Task<SignInResult> LoginAsync(AppUser user, string password)
repozytorium nie jest od takich rzeczy
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design#the-repository-pattern

2022-08-07 19:53 UTC, Madzionator commented on Lappka.Identity.Application/User/Commands/Handlers/ConfirmResetPasswordCommandHandler.cs
> +        if (!command.Password.Equals(command.ConfirmationToken))
moim zdaniem nie ma sensu przekazywać obydwu haseł niżej, skoro sprawdza się je na poziomie kontrolera

2022-08-07 20:12 UTC, anieckarz-src commented on Lappka.Identity.Api/Controllers/AuthController.cs
> +        return Ok();
Imo zależy od podejścia

2022-08-07 20:19 UTC, anieckarz-src commented on Lappka.Identity.Application/User/Commands/Handlers/ConfirmChangeEmailCommandHandler.cs
> +        var isCorrect = await _userRepository.CheckPasswordAsync(user, command.Password);
napierw same generowanie tokenu i wysłanie go na maila, później przekierowanie na formularz w którym trzeba podać nowy email i stare hasło. Jeżeli email i haslo są poprawne to email zostanie zmieniony

2022-08-07 20:25 UTC, anieckarz-src commented on Lappka.Identity.Application/User/Commands/Handlers/ConfirmResetPasswordCommandHandler.cs
> +        if (!command.Password.Equals(command.ConfirmationToken))
tu w ogole powinno być command.ConfirmPassword ;D Trzeba Adama dopytać

2022-08-08 11:01 UTC, Madzionator commented on Lappka.Identity.Api/Controllers/AuthController.cs
> +        return Ok();
Myślę, że to jednak standard

2023-02-16 15:38 UTC, closed without merging